language: rust
cache: cargo
env:
rust:
  - stable
  - beta
  - nightly
before_script:
  - rustup component add clippy-preview
script:
  - cargo test --verbose
  - cargo check --features "debug-images"
  - cargo clippy

notifications:
  email: false