language: rust
cache: cargo
env:
rust:
  - stable
  - beta
  - nightly
script:
  - cargo test --verbose
  - cargo check --features "debug-images"
matrix:
  fast_finish: true
  include:
    - rust: nightly-2018-05-29
      env:
        - CLIPPY_VERSION=0.0.206
      before_script:
        - cargo install clippy --version $CLIPPY_VERSION || echo "clippy already installed"
      script:
        - cargo clippy -- -D clippy

notifications:
  email: false