language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - cargo test --verbose
  - cargo check --features "debug-images"
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

notifications:
  email: false