language: rust
cache: cargo
env:
rust:
  - stable
  - beta
  - nightly
script:
  - cargo test --verbose
  - cargo check --features "debug-images"
matrix:
  fast_finish: true
  allow_failures:
    - env: NAME='cargo-coveralls'
  include:
    - rust: nightly-2018-05-29
      env:
        - CLIPPY_VERSION=0.0.206
      before_script:
        - cargo install clippy --version $CLIPPY_VERSION || echo "clippy already installed"
      script:
        - cargo clippy -- -D clippy
    - env:
        - NAME='cargo-coveralls'
        - RUST_LOG="cargo-travis=debug"
      sudo: required
      before_script:
        - cargo install cargo-update || echo "cargo-update already installed"
        - cargo install --git https://github.com/piderman314/cargo-travis.git --branch travis-pro --force || echo "cargo-travis already installed"
        - cargo install-update -a
      script:
        - |
          cargo build --verbose &&
          cargo coveralls --verbose
      addons:
        apt:
          packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - binutils-dev
            - cmake

notifications:
  email: false