[package]
name = "bardecoder"
version = "0.1.0"
authors = ["Mark Arts <piderman+github@gmail.com>"]

[dependencies]
image = "0.19.0"
log = "0.4"
failure = "0.1"
failure_derive = "0.1"
newtype_derive = "0.1.6"

[features]
default=[]
debug-images=[]
benchmark=[]